name: uttam-portfolio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.18.0

        # create .env file
      - name: create .env file
        run: |
            touch .env
            echo NEXT_PUBLIC_APPWRITE_ENDPOINT=${{ secrets.APPWRITE_ENDPOINT }} >> .env
            echo NEXT_PUBLIC_APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }} >> .env
            echo NEXT_PUBLIC_APPWRITE_API_KEY=${{ secrets.APPWRITE_API_KEY }} >> .env
          
        # npm installation
      - name: install npm dependencies
        run: npm install

          
        # npm test
      - name: run tests
        run: npm run test

        # npm build
      - name: build
        run: npm run build

        # Deploy to vercel
        
