name: uttam-portfolio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.18.0

        # npm installation
      - name: install npm dependencies
        run: npm install

        # npm test
      - name: run tests
        run: npm run test

        # npm build
      - name: build
        run: npm run build

        # Deploy to vercel
        
